### ISSUE TITLE
Añadir licencia.

### ISSUE THREAD

**Issue by Ismael-VC** [rodrigolece/RandomWalks.jl#1]
@rodrigolece te recomiendo añadas alguna licencia.

**Comment by rodrigolece** [comment]
Qué tan necesario crees que sea @Ismael-VC ? Ya sé que eventualmente sí me gustaría proteger que ésto fuera libre, pero ahorita todavía estoy jugando un poco. Y de licencias no sé absolutamente nada, me sugieres alguna?

**Comment by Ismael-VC** [comment]
Si te gustaría que fuera libre, que mejor que declararlo desde ahora, si en un futuro quieres cambiar la licencia y ya hay mucha gente que haya colaborado con código, se volvería un problema por que tendrías que pedir permiso a _todos_ para re licenciarlo.

Todo depende de que uso quieres que se le de a tu obra, la licencia GPLv2 es la mas usada, Julia por ejemplo usa la MIT.
