### ISSUE TITLE
Añadir mas comentarios y/o nombres descriptivos a variables.

### ISSUE THREAD

**Issue by Ismael-VC** [rodrigolece/RandomWalks.jl#5]
Te sugiero añadir mas comentarios, y/o usar nombres mas [mnemónicos](http://es.wikipedia.org/wiki/Mnem%C3%B3nico) y/o descriptivos para los identificadores, sobretodo aquellos de un solo carácter de longitud, ej.: `L`. Sin importar que tan obvia te parezca a ti (ahora) su función, ej,:

``` julia
type SmallWorldNet
    L::Int64
    Z::Int64
    p::Float64
    neighbours::Vector{Vector{Int64}}

    function SmallWorldNet(L::Int64)
        neighbours = Array(Vector{Int64},L)
        fill!(neighbours, [])
        new(L, 0, 0., neighbours)
    end
end
```

https://github.com/rodrigolece/caminantes-en-redes/blob/master/randomwalks.jl#L13

En este caso `L` se puede interpretar como longitud (numero) de dimensiones, una vez que se lee el constructor, pero `Z` y `p`, que son? no merecerán un mejor nombre? Es mas común leer código que escribirlo y tal vez ni tu mismo recuerdes a futuro, que significan todas tus abreviaturas.

**Comment by rodrigolece** [comment]
Estoy completamente de acuerdo, la idea para construir la red la saqué de un libro y se quedaron los nombre de las variables.
