### ISSUE TITLE
Añadir integración de coverage.

### ISSUE THREAD

**Issue by Ismael-VC** [rodrigolece/RandomWalks.jl#7]
Actualmente parece haber integración con:
- [Coveralls](https://coveralls.io/github/JuliaLang/julia)
- [Codecov](https://codecov.io/github/JuliaLang/julia?branch=master)

**Comment by rodrigolece** [comment]
@Ismael-VC, Codecov suena bien y estoy viendo [cómo configurarlo](https://codecov.io/guide) pero no tiene la información para Julia. Sabes qué tengo que hacer?

**Comment by rodrigolece** [comment]
No te preocupes, ya eché a andar Coveralls.

**Comment by Ismael-VC** [comment]
Excelente, disculpa que no el mensaje a tiempo, ahora a escribir pruebas!

**Comment by rodrigolece** [comment]
No te preocupes mano, tu ayuda ya había sido valiosa!
